version: 2
updates:
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - prma85
  versioning-strategy: increase
  ignore:
  - dependency-name: "@docusaurus/preset-classic"
    versions:
    - 2.0.0-alpha.70
    - 2.0.0-alpha.71
    - 2.0.0-alpha.72
    - 2.0.0-alpha.73
  - dependency-name: "@docusaurus/core"
    versions:
    - 2.0.0-alpha.70
    - 2.0.0-alpha.71
    - 2.0.0-alpha.72
    - 2.0.0-alpha.73
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
