# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr:
- master

jobs:
- job: Build
  workspace:
    clean: all
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'Install'
    workingDirectory: ./website

  - script: npm run build
    displayName: 'Build'
    workingDirectory: ./website

  - script: ln -s ../resources ./
    displayName: 'Creating symlink for exercices'
    workingDirectory: ./website/build/docs

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/website/build'
      contents: '**/*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
